---
- hosts: server
  tasks:
  - name: Install required packages
    apt: pkg={{item}} state=installed update_cache=true
    with_items:
    - joe
    - git
    - screen
    - strace
    - htop
    - ntop
    - rsync
    - sudo
    - python-software-properties
    - build-essential
    - libxml2
    - libxml2-dev
    - libyaml-dev
    - libxslt1-dev
    - git-core
    - redis-server
    - curl
    - wget
    - mysql-server-5.5
    - gcc
    - g++
    - make
    - binutils
    - erlang
    - elixir
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
  user: deployer
  sudo: yes
